// Generates out/sw.js after the static export.
//
// The precache list is read from the actual build output rather than hand-maintained: Next
// content-hashes its chunk filenames, so any hand-written list would be stale the moment
// anything changed — and a service worker that precaches a file that no longer exists fails
// to install at all, silently taking offline support with it.
//
// Runs as part of `bun run build`.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'out');

// Nothing here is worth caching, and sw.js must never cache itself.
const SKIP = new Set(['sw.js', '.DS_Store']);

function walk(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, files);
    else if (!SKIP.has(entry)) files.push(full);
  }
  return files;
}

let files;
try {
  files = walk(OUT);
} catch {
  console.error('generate-sw: no out/ directory — run the build first.');
  process.exit(1);
}

const hash = createHash('sha256');
const assets = files
  .map((file) => './' + relative(OUT, file).split(sep).join('/'))
  .sort();

for (const file of files.sort()) hash.update(readFileSync(file));
const version = hash.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/generate-sw.mjs — do not edit by hand.
//
// This worker exists so the app's own offline claim is true: everything is precached on the
// first visit, so a later load with no connection still works. It only ever handles
// same-origin GETs for the app's own files. It never sees a user's documents — those are
// read from disk and processed in the page, and the CSP (connect-src 'self') forbids sending
// them anywhere regardless.

const CACHE = 'pdf-merger-${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  // No skipWaiting: a new worker takes over only once every tab using the old one has closed.
  // The app dynamically imports pdf.js, so activating early and dropping the previous cache
  // could 404 a chunk out from under a page that is still running.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Every asset is either content-hashed or part of the shell, so the cache is authoritative.
  // A navigation that misses falls back to the cached shell, which is what makes a hard
  // refresh work offline.
  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request).catch(() => {
        if (request.mode === 'navigate') return caches.match('./index.html');
        throw new Error('offline and not cached');
      });
    }),
  );
});
`;

writeFileSync(join(OUT, 'sw.js'), sw);
console.log(`generate-sw: precaching ${assets.length} files (cache pdf-merger-${version})`);
